### ISSUE TITLE
There's nothing here

### ISSUE THREAD

**Issue by wilsonia** [ragreenburg/Python-Practice#1]
Just thought I'd let you know this repo is empty. Going to be pretty hard to practice python without any code.

**Comment by ragreenburg** [comment]
Bruh, I made this the couldn't figure out how to add code to it so I just made Gists haha.

**Comment by wilsonia** [comment]
"mastered git" my ass.

**Comment by ragreenburg** [comment]
I made this repo over a year ago, it took a minute to master.
